import matplotlib.pyplot as plt
import numpy as np 
import time as t

def get_bresenham_points(x1, y1, x2, y2):
    x_pixels = []
    y_pixels = []
    
    dy = abs(y2 - y1)
    dx = abs(x2 - x1)
    
    x = x1
    y = y1
    
    #choose which direction to step on like - circle octant code\
    step_x = 1 if x1 < x2 else -1
    step_y = 1 if y1 < y2 else -1
    
    
    if dx>dy:
        dS = 2*dy
        dT= 2*(dy-dx)
        d= 2*dy-dx
        for i in range(dx+1): #same as x <= x2, will not work while tried
            x_pixels.append(x)
            y_pixels.append(y)
            if(d<0):
                d+=dS
            else:
                d+=dT
                y+=step_y
            x+=step_x

    else:
        dS = 2*dx
        dT= 2*(dx-dy)
        d= 2*dx-dy
        for i in range(dy+1): #same as y <= y2
            x_pixels.append(x)
            y_pixels.append(y)
            if(d<0):
                d+=dS
            else:
                d+=dT
                x+=step_x   
            y+=step_y
                          
    return x_pixels, y_pixels



start_time = t.time()

x_list = []
y_list = []

total_lines = 500
plt_size = 200


for i in range(total_lines):
    x1=np.random.randint(0,plt_size)
    x2=np.random.randint(0,plt_size)
    y1=np.random.randint(0,plt_size)
    y2=np.random.randint(0,plt_size)
    
    x_point,y_point = get_bresenham_points(x1,y1,x2,y2)
    
    x_list.append(x_point)
    y_list.append(y_point)

ent_time = t.time()
time_taken = ent_time- start_time

for i in range(total_lines):
    plt.plot(x_list[i],y_list[i])

plt.title(f"{total_lines} Lines generated by Bresenham, Time taken:{time_taken:.5f}s")
plt.xlabel("X Axis")
plt.ylabel("Y Axis")
plt.show()