# 100 Random Circles using Bresenham's Algorithm
import matplotlib.pyplot as plt
import numpy as np  

def get_bresenham_circle_points(h, k, r):
    x_pixels = []
    y_pixels = []
    
    x = 0
    y = r
    d = 3 - 2 * r
    
    def plot_8_octants(X, Y):
        # (h, k) to shift the circle to wherever we want it
        points = [
            (h + X, k + Y), 
            (h - X, k + Y), 
            (h + X, k - Y), 
            (h - X, k - Y), 
            (h + Y, k + X), 
            (h - Y, k + X), 
            (h + Y, k - X), 
            (h - Y, k - X)  
        ]
        for px, py in points:
            x_pixels.append(px)
            y_pixels.append(py)

    while x <= y:
        plot_8_octants(x, y) #like setpixel
        
        if d < 0:
            d = d + 4 * x + 6
        else:
            d = d + 4 * (x - y) + 10
            y -= 1    
            
        x += 1        
        
    return x_pixels, y_pixels


total_circles = 100
grid_size = 500  
max_radius = 60   


# plt.figure(figsize=(8, 8)) 


for i in range(total_circles):
    h = np.random.randint(0, grid_size)
    k = np.random.randint(0, grid_size)
    r = np.random.randint(5, max_radius) # given min radius 5 
    
    x_list, y_list = get_bresenham_circle_points(h, k, r)
    
    plt.scatter(x_list, y_list, s=2) 

plt.title(f"{total_circles} Random Circles generated by Bresenham")
plt.xlabel("X Axis")
plt.ylabel("Y Axis")

plt.axis('equal') 
plt.grid(True, linestyle='--', alpha=0.5)

plt.show()