import matplotlib.pyplot as plt
import numpy as np 
import time as t

def get_dda_points(x1, y1, x2, y2):
    x_pixels = []
    y_pixels = []
    
    dy = y2 - y1
    dx = x2 - x1
        
    dS = int(2*dy)
    dT= int(2*(dy-dx)) 
    d= int(2*dy-dx)

                       
    x = x1
    y = y1
    
    while x <= x2:
        x_pixels.append(x)
        y_pixels.append(y)
        if(d<0):
            d+=dS
        else:
            d+=dT
            y+=1
        x+=1
                  
    return x_pixels, y_pixels



start_time = t.time()

x_list = []
y_list = []

total_lines = 500
plt_size = 200

total_point_in_one_line = 100

for i in range(total_lines):
    x1=np.random.randint(0,plt_size)
    x2=np.random.randint(0,plt_size)
    y1=np.random.randint(0,plt_size)
    y2=np.random.randint(0,plt_size)
    
    x_point,y_point = get_dda_points(x1,y1,x2,y2)
    
    x_list.append(x_point)
    y_list.append(y_point)

ent_time = t.time()
time_taken = ent_time- start_time

for i in range(total_lines):
    plt.plot(x_list[i],y_list[i])

plt.title(f"{total_lines} Lines generated by Bresenham, Time taken:{time_taken:.5f}s")
plt.xlabel("X Axis")
plt.ylabel("Y Axis")
plt.show()