import matplotlib.pyplot as plt
import numpy as np 
import time as t

def get_bresenham_points(x1, y1, x2, y2):
    x_pixels = []
    y_pixels = []
    
    # 1. Get absolute differences (Distances are always positive)
    dx = abs(x2 - x1)
    dy = abs(y2 - y1)
    
    # 2. Determine which direction we are stepping
    sx = 1 if x1 < x2 else -1
    sy = 1 if y1 < y2 else -1
    
    # Set our starting point
    x = x1
    y = y1

    # --- CASE 1: Gentle Slope (X is the driving axis) ---
    if dx > dy:
        # Standard textbook Bresenham logic
        d = 2 * dy - dx
        dS = 2 * dy
        dT = 2 * (dy - dx)
        
        while x != x2:
            x_pixels.append(x)
            y_pixels.append(y)
            
            if d < 0:
                d += dS
            else:
                y += sy  # Use 'sy' instead of +1 so it can draw downwards!
                d += dT
                
            x += sx      # Use 'sx' instead of +1 so it can draw backwards!
            
        # Append the final point
        x_pixels.append(x)
        y_pixels.append(y)

    # --- CASE 2: Steep Slope (Y is the driving axis) ---
    else:
        # The exact same logic, but X and Y are flipped!
        d = 2 * dx - dy
        dS = 2 * dx
        dT = 2 * (dx - dy)
        
        while y != y2:
            x_pixels.append(x)
            y_pixels.append(y)
            
            if d < 0:
                d += dS
            else:
                x += sx  # Move X
                d += dT
                
            y += sy      # Move Y (Driving axis)
            
        # Append the final point
        x_pixels.append(x)
        y_pixels.append(y)
                  
    return x_pixels, y_pixels

# ==========================================
# MAIN EXECUTION
# ==========================================

start_time = t.time()

x_list = []
y_list = []

total_lines = 500
plt_size = 200

for i in range(total_lines):
    # Perfect, using randint for exact pixels!
    x1 = np.random.randint(0, plt_size)
    x2 = np.random.randint(0, plt_size)
    y1 = np.random.randint(0, plt_size)
    y2 = np.random.randint(0, plt_size)
    
    x_point, y_point = get_bresenham_points(x1, y1, x2, y2)
    
    x_list.append(x_point)
    y_list.append(y_point)

end_time = t.time()
time_taken = end_time - start_time


for i in range(total_lines):
    plt.plot(x_list[i],y_list[i])

plt.title(f"{total_lines} Lines generated by Bresenham\nTime taken: {time_taken:.5f}s")
plt.xlabel("X Axis (Pixels)")
plt.ylabel("Y Axis (Pixels)")

plt.xlim(0, plt_size)
plt.ylim(0, plt_size)

plt.show()